GPUID: 0
WORKERS: 4
PRINT_FREQ: 50
SAVE_FREQ: 50
PIN_MEMORY: False
OUTPUT_DIR: 'output'

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: OWN
#  ROOT: "/home/hyli/project/OCR/LPRNet_Pytorch/data/train/"
#  JSON_FILE: {'train': '/home/hyli/project/OCR/CRNN_Chinese_Characters_Rec/lib/dataset/train_all.txt', 'val': '/home/hyli/project/OCR/CRNN_Chinese_Characters_Rec/lib/dataset/test_all.txt'}
  ROOT: "/home/hyli/project/OCR/OCR_datasets/CCPD_database/ccpd_train/"
  JSON_FILE: {'train': '/home/hyli/project/OCR/CRNN_Chinese_Characters_Rec/lib/dataset/train_ccpd_all.txt', 'val': '/home/hyli/project/OCR/CRNN_Chinese_Characters_Rec/lib/dataset/test_ccpd_all.txt'}
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588
  ALPHABETS: ''

TRAIN:
  BATCH_SIZE_PER_GPU: 1024
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME:
    IS_RESUME: False
    FILE: '/home/hyli/project/OCR/CRNN_Chinese_Characters_Rec/output/OWN/crnn/2021-02-04-19-29/checkpoints/checkpoint_48_acc_0.7792.pth'
  OPTIMIZER: 'adam'
  LR: 0.0001
  WD: 0.0
  LR_STEP: [30,60,80]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:
  FINETUNE:
    IS_FINETUNE: True
    FINETUNE_CHECKPOINIT: '/home/hyli/project/OCR/CRNN_Chinese_Characters_Rec/output/OWN/crnn/2021-02-05-15-38/checkpoints/checkpoint_96_acc_0.9042.pth'
    FREEZE: False

TEST:
  BATCH_SIZE_PER_GPU: 1024
  SHUFFLE: True  # for random test rather than test on the whole validation set
  NUM_TEST_BATCH: 1000
  NUM_TEST_DISP: 10

MODEL:
  NAME: 'crnn'
  IMAGE_SIZE:
    OW: 280. # origial width: 280
    H: 32
    W: 160   # resized width: 160
  NUM_CLASSES: 0
  NUM_HIDDEN: 84
  COUNT_NUM: 1
  IS_PRUNDED: false

